export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOAD_BUCKETLIST_SUCCESS = 'LOAD_BUCKETLIST_SUCCESS';
export const CREATE_BUCKETLIST_SUCCESS = 'CREATE_BUCKETLIST_SUCCESS';
export const DELETE_BUCKETLIST_SUCCESS = 'DELETE_BUCKETLIST_SUCCESS';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';